### PR TITLE
Bugfix null parameter in error handler

### LINKED ISSUE #61: error_handler may receive incorrect parameter types for $e
Calls to error_handler without a second parameter will trigger a hard fault. auth.php calls error_handler without a second parameter. This causes a crash when $e->__toString() is called.

error_handler should check $e to make sure it is really a Throwable type.

### PR DESCRIPTION
**Pull request by infomaniac50**
Fixes #61

~~Merge after my previous request. This on is stacked on top of the last bug fix.~~

I'll do a rebase if it's needed.

### CODE REVIEW

**Comment by infomaniac50** [comment]
I've never tried to merge two pull requests at the same time. Git is a bit confusing at times.

**Comment by infomaniac50** [comment]
Are you holding off on this pull request? 

I see you added composer in the new feature branch. Is this still relevant?

**Comment by eerotal** [comment]
Oh, I'm just waiting for you to make the changes I requested so I can merge this. Sure it's still relevant.

**Comment by eerotal** [comment]
Oh sorry, I forgot to submit the review so you haven't seen it. It should now be visible.

**Comment by eerotal** [comment]
Okay, this is now "merged". I had to resort to cherry-picking the commits into v1.x.x instead of merging because of the way I use the different branches. The problem here is that this PR is based on top of all the commits in next but it should also be merged into v1.x.x. This causes problems because I obviously can't merge this PR into v1.x.x without also merging all the commits from next. I also can't merge this PR into next and then cherry-pick the commits from next into v1.x.x because then the repo will be riddled with merge conflicts. That's why I had to cherry-pick this PR into v1.x.x and then merge that into next.

I don't think I have said this anywhere but from now on when you create PRs, please base them on the "oldest" branch that should still have the fix applied. In this case the right branch would be v1.x.x. This makes merging easy for me because then I can merge the PR straight into v1.x.x and then merge v1.x.x into next to include the fixes in the next release aswell.

**Pull request closed without merging**
